// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR1nSz968AQDZh553yvZSExXf0V-8doOg',
    appId: '1:352594697134:web:20adf4476b4ff9dcd4c63f',
    messagingSenderId: '352594697134',
    projectId: 'testproject-43837',
    authDomain: 'testproject-43837.firebaseapp.com',
    storageBucket: 'testproject-43837.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESIETyg9IPjVKJdNdK8fTCDm7mYSq1iM',
    appId: '1:352594697134:android:9f1c5260d07f542cd4c63f',
    messagingSenderId: '352594697134',
    projectId: 'testproject-43837',
    storageBucket: 'testproject-43837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_kGj02oZg8vWMyoKctTHtAW3EsqKAPE',
    appId: '1:352594697134:ios:d976d366b12a8ec7d4c63f',
    messagingSenderId: '352594697134',
    projectId: 'testproject-43837',
    storageBucket: 'testproject-43837.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_kGj02oZg8vWMyoKctTHtAW3EsqKAPE',
    appId: '1:352594697134:ios:d976d366b12a8ec7d4c63f',
    messagingSenderId: '352594697134',
    projectId: 'testproject-43837',
    storageBucket: 'testproject-43837.appspot.com',
    iosBundleId: 'com.example.testProject',
  );
}
